baseurl: null
copyrightYear: 2025
demos: /resources/demos
docs: https://www.gafferhq.org/documentation
future: false
gems:
- jekyll-paginate
google_analytics: UA-125947352-1
images: /resources/images
latestGafferVersion: 1.6.6.1
paginate: 1
permalink: /news/:title/
